#!/bin/sh

_fail="\033[31m"
_good="\033[32m"
_rset="\033[0m"

set -e

if command -v rsync > /dev/null ; then
	RSYNC='rsync'
else
	RSYNC='openrsync'
fi

if command -v doas > /dev/null ; then
	_doas=doas
else
	_doas=sudo
fi

_resourcedir="$HOME"/sources/backup

dirlist="${_resourcedir}"/list-backup.txt

backup() {
	if [ -n "$2" ] ; then
		_mntpoint="$2"
	else
		exit 1
	fi

	nr=$(grep -c '' "$dirlist")
	i=0

	while IFS= read -r d ; do
		i=$((i+1))
		"$RSYNC" -av --delete "$HOME/$d" "${_mntpoint}/" \
			&& printf "${_good}%s${_rset}\n\n" "---> Synced $i/${nr}" \
			|| exit 1
	done < "$dirlist"
	[ -f "$HOME"/mbox ] && cp "$HOME"/mbox "${_mntpoint}"
}

check_bitrot() {
	checklist="${_resourcedir}"/list-bitrot.txt
	nr=$(grep -c '' "$checklist")
	i=0
	while IFS= read -r d ; do
		i=$((i+1))
		cd "$HOME"/"$d" && bitrot \
			&& printf "${_good}%s${_rset}\n\n" "---> checked bitrot $i/${nr} ($HOME/$d)" \
			|| exit 1
	done < "$checklist"
}

collect_dotfiles() {
	if mkdir -p "${_dotdir}" ; then
		printf "${_good}[1/5] ----- Created ${_dotdir}.${_rset}\n\n"
	else
		printf "${_fail}[1/5] ----- Creating ${_dotdir} failed.${_rset}\n\n"
		exit 1
	fi

	if "${_resourcedir}"/collect_config ; then
		printf "${_good}[2/5] ----- Collected configurations.${_rset}\n\n"
	else
		printf "${_fail}[2/5] ----- Collecting configurations failed.${_rset}\n\n"
		exit 1
	fi

	if "${_resourcedir}"/collect_privconfig ; then
		printf "${_good}[3/5] ----- Collected privileged configurations.${_rset}\n\n"
	else
		printf "${_fail}[3/5] ----- Collecting privileged configurations failed.${_rset}\n\n"
		exit 1
	fi

	if "${_resourcedir}"/collect_installs ; then
		printf "${_good}[4/5] ----- Created list of installed packages.${_rset}\n\n"
	else
		printf "${_fail}[4/5] ----- Creating list of installed packages failed.${_rset}\n\n"
		exit 1
	fi

	if "${_resourcedir}"/collect_data ; then
		printf "${_good}[5/5] ----- Collected data.${_rset}\n\n"
	else
		printf "${_fail}[5/5] ----- Collecting data failed.${_rset}\n\n"
		exit 1
	fi
}

prepare_backup() {
	if pgrep mutt > /dev/null ; then
		echo "mutt is still running." \
			&& exit 1
	fi
}

prepare_collecting_dotfiles() {
	if pgrep mutt > /dev/null ; then
		echo "mutt is still running." \
			&& exit 1
	else
		_dotdir="$HOME"/dotfiles/"$(date +%F)"
		export _dotdir
		[ -d "${_dotdir}" ] \
			&& echo "${_dotdir} already exists. Do some clean-up!" \
			&& exit 1
	fi
}

usage() { cat << USAGE
${0##*/} - a selection of scripts for reliable backups
usage: ${0##*/}	all [dir] -> backup all directories to [dir]
		bitrot    -> check for bitrot in selected directories
		dotfiles  -> collect dotfiles"
USAGE
	exit 1
}

set +e

case $1 in
all)
	prepare_backup
	backup "$@"
	;;
bitrot)
	check_bitrot
	;;
dotfiles)
	prepare_collecting_dotfiles
	collect_dotfiles
	;;
*)
	usage
	;;
esac
