#!/bin/sh

_fail="\033[31m"
_good="\033[32m"
_rset="\033[0m"

if command -v rsync > /dev/null ; then
	RSYNC='rsync'
else
	RSYNC='openrsync'
fi

if command -v doas > /dev/null ; then
	_doas=doas
else
	_doas=sudo
fi

_resourcedir="$HOME"/sources/backup

dirlist="${_resourcedir}"/directories.txt

backup() {
	if [ -n "$2" ] ; then
		_mntpoint="$2"
	else
		exit 1
	fi

	nr=$(grep -c '' "$dirlist")
	i=0

	while IFS= read -r d ; do
		i=$((i+1))
		"$RSYNC" -av --delete "$HOME"/"$d" "${_mntpoint}" \
			&& printf '%s\n' "${_good}---> synced $i/${nr}${_rset}" \
			|| exit 1
		echo "$d: $(find "$HOME"/"$d" -type f | wc -l)" >> "$HOME"/checkfilenumber-src.txt
		echo "$d: $(find "${_mntpoint}"/"$d" -type f | wc -l)" >> "$HOME"/checkfilenumber-dest.txt
	done < "$dirlist"
	[ -f "$HOME"/mbox ] && cp "$HOME"/mbox "${_mntpoint}"

	echo "Check file number:"
	diff "$HOME"/checkfilenumber-src.txt "$HOME"/checkfilenumber-dest.txt \
		&& echo "${_good}--- file number is consistent. ---${_rset}" \
		&& rm "$HOME"/checkfilenumber-*.txt
}

check_bitrot() {
	checklist='Pictures Wichtig documents media'
	nr=4
	i=0
	for d in $checklist ; do
		i=$((i+1))
		cd "$HOME"/"$d" && bitrot \
			&& printf '%s\n' "${_good}---> checked bitrot $i/${nr} ($HOME/$d)${_rset}" \
			|| exit 1
	done
}

scan_collection() {
	echo "Scan collected dotfiles:"
	"${_doas}" freshclam && clamscan -riz --scan-pdf=yes "${_dotdir}"
}

collect_dotfiles() {
	if mkdir -p "${_dotdir}" ; then
		echo "${_good}[1/6] ----- Created ${_dotdir}.${_rset}"
	else
		echo "${_fail}[1/6] ----- Creating ${_dotdir} failed.${_rset}" 
		exit 1
	fi

	if "${_resourcedir}"/collect_config ; then
		echo "${_good}[2/6] ----- Collected configurations.${_rset}"
	else
		echo "${_fail}[2/6] ----- Collecting configurations failed.${_rset}"
		exit 1
	fi

	if "${_resourcedir}"/collect_privconfig ; then
		echo "${_good}[3/6] ----- Collected privileged configurations.${_rset}"
	else
		echo "${_fail}[3/6] ----- Collecting privileged configurations failed.${_rset}"
		exit 1
	fi

	if "${_resourcedir}"/collect_installs ; then
		echo "${_good}[4/6] ----- Created list of installed packages.${_rset}"
	else
		echo "${_fail}[4/6] ----- Creating list of installed packages failed.${_rset}"
		exit 1
	fi

	if "${_resourcedir}"/collect_data ; then
		echo "${_good}[5/6] ----- Collected data.${_rset}"
	else
		echo "${_fail}[5/6] ----- Collecting data failed.${_rset}"
		exit 1
	fi

	if scan_collection ; then
		echo "${_good}[6/6] ----- Clamscan: No infected files found.${_rset}"
	else
		echo "${_fail}[6/6] ----- Clamscan: Infected files found.${_rset}"
		exit 1
	fi
}

prepare_backup() {
	if pgrep mutt > /dev/null ; then
		echo "mutt is still running." \
			&& exit 1
	fi
}

prepare_collecting_dotfiles() {
	if pgrep mutt > /dev/null ; then
		echo "mutt is still running." \
			&& exit 1
	else
		_dotdir="$HOME"/dotfiles/"$(date +%F)"
		export _dotdir
		[ -d "${_dotdir}" ] \
			&& echo "${_dotdir} already exists. Do some clean-up!" \
			&& exit 1
	fi
}

usage() {
	echo "\
backup has the following options:
all	[dir]	-> backup all directories to [dir]
bitrot		-> check for bitrot in selected directories
dotfiles	-> collect dotfiles"
exit 1
}

case $1 in
all)
	prepare_backup
	backup "$@"
	;;
bitrot)
	check_bitrot
	;;
dotfiles)
	prepare_collecting_dotfiles
	collect_dotfiles
	;;
*)
	usage
	;;
esac
