#!/bin/sh

echo "Start collecting installed packages:"
_installdir="${_dotdir}"/installed_packages

if [ "$(uname -s)" = "OpenBSD" ] ; then
	pkg_info -tz >> "${_installdir}"/openbsd_pkgs.txt \
		|| exit 1
elif [ "$(awk -F "(\"| )" 'NR == 1 { print $2 }' /etc/os-release)" = "Fedora" ] ; then
	dnf history userinstalled >> "${_installdir}"/fedora_pkgs.txt \
		|| exit 1
	flatpak list >> "${_installdir}"/flatpaks.txt \
		|| exit 1
else
	echo "OS is unknown. Aborting..." && exit 1
fi